name: maven build

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build-artifacts:
    uses: ./.github/workflows/build-artifacts.yml
    with:
      ref: ${{ github.ref_name }}
      is_tag: false
    secrets: inherit
